# Generated by Django 4.2.30 on 2026-09-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_booking_confirmed_by_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(verbose_name='Endpoint (URL push-сервиса)')),
                ('p256dh', models.TextField(verbose_name='Публичный ключ клиента (p256dh)')),
                ('auth', models.TextField(verbose_name='Auth-секрет клиента')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='masters.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Push-подписка',
                'verbose_name_plural': 'Push-подписки',
                'unique_together': {('master', 'endpoint')},
            },
        ),
    ]
