# Generated by Django 4.2.30 on 2026-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='token',
            field=models.CharField(blank=True, help_text='Уникальный токен для управления записью клиентом', max_length=32, null=True, unique=True, verbose_name='Токен для клиента'),
        ),
    ]
