# Generated by Django 4.2.30 on 2026-09-27 13:25

import secrets
from django.db import migrations


def fill_tokens(apps, schema_editor):
    Booking = apps.get_model('masters', 'Booking')
    
    for booking in Booking.objects.filter(token__isnull=True):
        # Генерируем уникальный токен
        while True:
            token = secrets.token_urlsafe(16)
            if not Booking.objects.filter(token=token).exists():
                booking.token = token
                booking.save(update_fields=['token'])
                break


def reverse_fill(apps, schema_editor):
    # Откат — обнуляем токены
    Booking = apps.get_model('masters', 'Booking')
    Booking.objects.update(token=None)


class Migration(migrations.Migration):
    dependencies = [
        ('masters', '0006_booking_token'), 
    ]
    
    operations = [
        migrations.RunPython(fill_tokens, reverse_fill),
    ]