# Generated by Django 4.2.30 on 2026-09-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_fill_booking_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('check_id', models.CharField(blank=True, max_length=100, verbose_name='ID проверки звонка')),
                ('call_phone', models.CharField(blank=True, max_length=20, verbose_name='Номер для звонка')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to='masters.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Сессия клиента',
                'verbose_name_plural': 'Сессии клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
